version: "3.8"

services:
  poc-quarkus-quickfix-acceptor:
    container_name: poc-quarkus-quickfix-acceptor
    image: poc-quarkus-quickfix-acceptor:latest    
    build:
      context: ./poc-fix-acceptor/
      dockerfile: ./src/main/docker/Dockerfile.fast-jar
      
    ports:
      - 8090:8090
    networks:
      - poc-quarkus-quickfix-net
    environment:
      - QUICKFIX=quickfix=[default],
          [session],
          BeginString=FIX.4.4,
          SenderCompID=EXEC,
          TargetCompID=BANZAI,
          ConnectionType=acceptor,
          StartTime=00:00:00,
          EndTime=00:00:00,
          SocketAcceptPort=9880,
          ScreenLogShowHeartBeats=Y

  poc-quarkus-quickfix-initiator:
    container_name: poc-quarkus-quickfix-initiator
    image: poc-quarkus-quickfix-initiator:latest    
    build:
      context: ./poc-fix-initiator
      dockerfile: ./src/main/docker/Dockerfile.fast-jar
    environment:      
      - QUICKFIX=[default],
          [session],
          BeginString=FIX.4.4,
          SenderCompID=BANZAI,
          TargetCompID=EXEC,
          ConnectionType=initiator,
          StartTime=00:00:00,
          EndTime=00:00:00,
          ReconnectInterval=5,
          HeartBtInt=30,
          SocketConnectHost=poc-quarkus-quickfix-acceptor,
          SocketConnectPort=9880,
          ScreenLogShowHeartBeats=Y
    ports:
      - 8080:8080
    networks:
      - poc-quarkus-quickfix-net

networks:
  poc-quarkus-quickfix-net:
    driver: bridge
